services:
  server:
    image: lockkeep-server
    labels:
      - "traefik.http.routers.lockkeep-server.rule=Host(`api.lockkeep.localhost`)"
      - "traefik.http.services.lockkeep-server.loadbalancer.server.port=8000"
    # restart: always
    ports:
      - 8000:8000
    depends_on:
      mongo1:
        condition: service_healthy
      mongo2:
        condition: service_healthy
      mongo3:
        condition: service_healthy
    env_file:
      - .env
    networks:
      - lockkeep-network

networks:
  lockkeep-network:
    external: true
